#!/bin/bash

set -eu

echo "Branch: ${TRAVIS_BRANCH}"

[[ $TRAVIS_REPO_SLUG = "unionfes/unionfes.github.io" ]] || exit 0
[[ $TRAVIS_BRANCH != "master" ]] && {
  echo "Deployment is skipped"
  exit 0
}

cd build

# Decrypt deploy SSH key

mkdir -p $HOME/.ssh
chmod 700 $HOME/.ssh
openssl aes-256-cbc \
  -K $encrypted_97c6636764c6_key \
  -iv $encrypted_97c6636764c6_iv \
  -in id_rsa.enc \
  -out $HOME/.ssh/id_rsa \
  -d
chmod 600 $HOME/.ssh/id_rsa

# Configure git

git init .
git config user.name travis
git config usre.email ci@travis-ci.org
git remote add origin ssh://git@github.com/unionfes/unionfes.github.io.git

# Deploy

git add --all
git commit -m "Automated commit at `date` by Travis"
git push -f origin master

echo "Deployment succeeded"
